import {
  Injectable,
  InternalServerErrorException,
  Logger,
  NotFoundException,
} from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import {
  DeleteObjectCommand,
  GetObjectCommand,
  PutObjectCommand,
  S3Client,
} from '@aws-sdk/client-s3';
import { getSignedUrl } from '@aws-sdk/s3-request-presigner';
import { randomBytes } from 'crypto';
import { createReadStream } from 'fs';
import { copyFile, mkdir, rm, stat, writeFile } from 'fs/promises';
import { dirname, join, resolve, sep } from 'path';

export type StorageDriver = 's3' | 'local';

// Keys are generated by us: lowercase path segments + random name + image extension
const KEY_PATTERN = /^[a-z0-9-]+(\/[a-z0-9-]+)*\.(jpg|png|webp)$/;

export const isValidStorageKey = (key: string) =>
  key.length <= 300 && KEY_PATTERN.test(key) && !key.includes('..');

// Private files (report exports): never served publicly, only through short-lived
// signed links issued after a permission check
const PRIVATE_KEY_PATTERN =
  /^private\/[a-z0-9-]+(\/[a-z0-9-]+)*\.(csv|xlsx|pdf)$/;

export const isValidPrivateKey = (key: string) =>
  key.length <= 300 && PRIVATE_KEY_PATTERN.test(key) && !key.includes('..');

/**
 * Object storage for uploaded files (product images).
 * - S3 or any S3-compatible service (MinIO, R2, Railway buckets) when configured
 * - a local directory otherwise (development), served by StorageController
 * Stored URLs are stable: either the bucket's public URL, or this API's
 * /storage/files/<key> route (which redirects to a short-lived presigned URL for S3).
 */
@Injectable()
export class StorageService {
  private readonly logger = new Logger(StorageService.name);
  readonly driver: StorageDriver;
  private readonly s3?: S3Client;
  private readonly bucket?: string;
  private readonly localRoot: string;
  private readonly privateRoot: string;
  private readonly publicBaseUrl: string;
  private readonly s3PublicUrl?: string;
  readonly presignSeconds: number;

  constructor(private config: ConfigService) {
    // Validated config may hold numbers (PORT), so stringify before trimming
    const get = (name: string) => {
      const value = this.config.get<string | number | boolean>(name);
      return value === undefined || value === null ? '' : `${value}`.trim();
    };
    const s3Configured = [
      'S3_ENDPOINT',
      'S3_BUCKET',
      'S3_ACCESS_KEY_ID',
      'S3_SECRET_ACCESS_KEY',
    ].every((name) => get(name));
    const requested = get('STORAGE_DRIVER') as StorageDriver | '';
    const deployed = ['production', 'staging'].includes(get('NODE_ENV'));
    // Explicit STORAGE_DRIVER wins; otherwise S3 whenever it's configured in a deployed
    // environment, and local disk in development/test
    this.driver =
      requested === 's3' || requested === 'local'
        ? requested
        : s3Configured && deployed
          ? 's3'
          : 'local';

    if (this.driver === 's3') {
      if (!s3Configured) {
        throw new Error(
          'STORAGE_DRIVER=s3 needs S3_ENDPOINT, S3_BUCKET, S3_ACCESS_KEY_ID and S3_SECRET_ACCESS_KEY',
        );
      }
      this.bucket = get('S3_BUCKET');
      this.s3 = new S3Client({
        endpoint: get('S3_ENDPOINT'),
        region: get('S3_REGION') || 'us-east-1',
        forcePathStyle: get('S3_FORCE_PATH_STYLE') === 'true',
        credentials: {
          accessKeyId: get('S3_ACCESS_KEY_ID'),
          secretAccessKey: get('S3_SECRET_ACCESS_KEY'),
        },
      });
      this.s3PublicUrl = get('S3_PUBLIC_URL').replace(/\/+$/, '') || undefined;
    }

    this.localRoot = resolve(
      get('STORAGE_LOCAL_DIR') || join(process.cwd(), 'uploads'),
    );
    // Outside the public root: StorageController never serves these
    this.privateRoot = resolve(
      get('STORAGE_PRIVATE_DIR') || join(process.cwd(), 'private-files'),
    );
    const port = get('PORT') || '3000';
    const prefix = (get('API_PREFIX') || 'api/v1').replace(/^\/+|\/+$/g, '');
    this.publicBaseUrl = (
      get('STORAGE_PUBLIC_BASE_URL') || `http://localhost:${port}/${prefix}`
    ).replace(/\/+$/, '');
    this.presignSeconds = Number(get('S3_PRESIGN_EXPIRES') || 3600);
  }

  /** A new random key under the given prefix, e.g. products/<tenant>/<product>/<random>.webp */
  newKey(prefix: string, extension: string): string {
    const key = `${prefix}/${randomBytes(16).toString('hex')}.${extension}`;
    if (!isValidStorageKey(key)) {
      throw new InternalServerErrorException('Invalid storage key');
    }
    return key;
  }

  /** Stable URL stored in the database and used directly in <img src> */
  publicUrl(key: string): string {
    if (this.driver === 's3' && this.s3PublicUrl) {
      return `${this.s3PublicUrl}/${key}`;
    }
    return `${this.publicBaseUrl}/storage/files/${key}`;
  }

  async put(key: string, body: Buffer, contentType: string): Promise<void> {
    if (this.s3) {
      await this.s3.send(
        new PutObjectCommand({
          Bucket: this.bucket,
          Key: key,
          Body: body,
          ContentType: contentType,
          CacheControl: 'public, max-age=31536000, immutable',
        }),
      );
      return;
    }
    const path = this.localPath(key);
    await mkdir(dirname(path), { recursive: true });
    await writeFile(path, body, { flag: 'wx' });
  }

  /** Best effort: a missing object is not an error */
  async delete(key: string): Promise<void> {
    try {
      if (this.s3) {
        await this.s3.send(
          new DeleteObjectCommand({ Bucket: this.bucket, Key: key }),
        );
      } else {
        await rm(this.localPath(key), { force: true });
      }
    } catch (error) {
      this.logger.warn(
        `Could not delete ${key}: ${error instanceof Error ? error.message : String(error)}`,
      );
    }
  }

  /** Short-lived signed GET URL (S3 driver) */
  async presignedUrl(key: string): Promise<string> {
    if (!this.s3) {
      throw new NotFoundException();
    }
    return getSignedUrl(
      this.s3,
      new GetObjectCommand({ Bucket: this.bucket, Key: key }),
      { expiresIn: this.presignSeconds },
    );
  }

  // ---- Private files (report exports) ----

  /** A new random private key, e.g. private/exports/<tenant>/<random>.csv */
  newPrivateKey(prefix: string, extension: string): string {
    const key = `private/${prefix}/${randomBytes(16).toString('hex')}.${extension}`;
    if (!isValidPrivateKey(key)) {
      throw new InternalServerErrorException('Invalid storage key');
    }
    return key;
  }

  /** Store a local file (e.g. a generated export) under a private key */
  async putPrivateFile(
    key: string,
    filePath: string,
    contentType: string,
  ): Promise<void> {
    if (this.s3) {
      const { size } = await stat(filePath);
      await this.s3.send(
        new PutObjectCommand({
          Bucket: this.bucket,
          Key: key,
          Body: createReadStream(filePath),
          ContentLength: size,
          ContentType: contentType,
          CacheControl: 'private, no-store',
        }),
      );
      return;
    }
    const path = this.privateLocalPath(key);
    await mkdir(dirname(path), { recursive: true });
    await copyFile(filePath, path);
  }

  /**
   * Signed download URL valid `seconds` (S3 driver). Null with local storage:
   * the caller serves the file itself (privateLocalPath) behind its own check.
   */
  async privateDownloadUrl(
    key: string,
    filename: string,
    seconds: number,
  ): Promise<string | null> {
    if (!isValidPrivateKey(key)) throw new NotFoundException();
    if (!this.s3) return null;
    return getSignedUrl(
      this.s3,
      new GetObjectCommand({
        Bucket: this.bucket,
        Key: key,
        ResponseContentDisposition: `attachment; filename="${filename.replace(/["\\\r\n]/g, '')}"`,
      }),
      { expiresIn: seconds },
    );
  }

  /** Best effort: a missing object is not an error */
  async deletePrivate(key: string): Promise<void> {
    if (!isValidPrivateKey(key)) return;
    try {
      if (this.s3) {
        await this.s3.send(
          new DeleteObjectCommand({ Bucket: this.bucket, Key: key }),
        );
      } else {
        await rm(this.privateLocalPath(key), { force: true });
      }
    } catch (error) {
      this.logger.warn(
        `Could not delete ${key}: ${error instanceof Error ? error.message : String(error)}`,
      );
    }
  }

  /** Absolute path of a private key (local driver); rejects anything that escapes */
  privateLocalPath(key: string): string {
    if (!isValidPrivateKey(key)) {
      throw new NotFoundException();
    }
    const path = resolve(this.privateRoot, key);
    if (!path.startsWith(this.privateRoot + sep)) {
      throw new NotFoundException();
    }
    return path;
  }

  get localDirectory(): string {
    return this.localRoot;
  }

  /** Absolute path of a key inside the local root; rejects anything that escapes it */
  localPath(key: string): string {
    if (!isValidStorageKey(key)) {
      throw new NotFoundException();
    }
    const path = resolve(this.localRoot, key);
    if (!path.startsWith(this.localRoot + sep)) {
      throw new NotFoundException();
    }
    return path;
  }
}
